[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Alexander Belikov <abelikov@gmail.com>"]
description = "bio / sci property entity linker"
license = "BSD 3"
name = "pelinker"
packages = [{include = "pelinker"}]
readme = "README.md"
version = "0.1.3"

[tool.poetry.dependencies]
faiss-cpu = "1.8.0"
flask = "^3.0.3"
flask-compress = "^1.15"
flask-cors = "^4.0.1"
flask-restful = "^0.3.10"
joblib = "^1.4.2"
numpy = "^1.26.4"
pandas = "^2.2.2"
plotly = "^6.2.0"
pyarrow = "^20.0.0"
python = "^3.10"
rdflib = "^7.0.0"
sentence-transformers = "^3.0.1"
spacy = {extras = ["cpu"], version = "^3.7.5"}
torch = {url = "https://download.pytorch.org/whl/cpu/torch-2.3.1%2Bcpu-cp310-cp310-linux_x86_64.whl"}
transformers = "^4.41.2"
umap-learn = "^0.5.9.post2"
waitress = "^3.0.2"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
networkx = "^3.3"
pre-commit = "^4.0.1"
pylint = "^3.2.3"
pytest = "^8.2.2"
scikit-learn = "^1.5.0"
seaborn = "^0.13.2"
